version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:latest
    container_name: advanced-appointment-postgres
    environment:
      POSTGRES_DB: advanced_appointment_booking
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Redis Cache
  redis:
    image: redis:latest
    container_name: advanced-appointment-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # Eureka Server
  eureka-server:
    image: advanced-appointment-eureka-server
    container_name: advanced-appointment-eureka
    ports:
      - "8761:8761"
    depends_on:
      - postgres
      - redis

  # User Service
  user-service:
    build: ./user-service
    container_name: advanced-appointment-user-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/advanced_appointment_booking
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - postgres
      - redis
      - eureka-server

  # Appointment Service
  appointment-service:
    build: ./appointment-service
    container_name: advanced-appointment-service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/advanced_appointment_booking
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - postgres
      - redis
      - eureka-server

  # Notification Service
  notification-service:
    build: ./notification-service
    container_name: advanced-appointment-notification-service
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/advanced_appointment_booking
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - postgres
      - redis
      - eureka-server

  # Analytics Service
  analytics-service:
    build: ./analytics-service
    container_name: advanced-appointment-analytics-service
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/advanced_appointment_booking
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - postgres
      - redis
      - eureka-server

  # Healthcare Service
  healthcare-service:
    build: ./healthcare-service
    container_name: advanced-appointment-healthcare-service
    ports:
      - "8085:8085"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/advanced_appointment_booking
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - postgres
      - redis
      - eureka-server

  # Resource Service
  resource-service:
    build: ./resource-service
    container_name: advanced-appointment-resource-service
    ports:
      - "8086:8086"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/advanced_appointment_booking
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - postgres
      - redis
      - eureka-server

volumes:
  postgres_data:
  redis_data: 