server:
  port: ${SERVER_PORT:8081}
  servlet:
    context-path: /api
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never

spring:
  application:
    name: advanced-appointment-user-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:advanced_appointment_booking}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: ${DB_POOL_SIZE:10}
      minimum-idle: ${DB_MIN_IDLE:5}
      idle-timeout: 300000
      connection-timeout: 20000
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: UTC
    default-property-inclusion: non_null

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

jwt:
  secret: ${JWT_SECRET:your-secret-key-here-should-be-very-long-and-secure-for-advanced-appointment-system}
  expiration: ${JWT_EXPIRATION:86400000} # 24 hours in milliseconds

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

# Logging configuration
logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
    com.elyes.advanced.appointment: ${LOG_LEVEL_APP:DEBUG}
    org.springframework.web: ${LOG_LEVEL_WEB:INFO}
    org.hibernate: ${LOG_LEVEL_HIBERNATE:INFO}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/user-service.log
    max-size: 10MB
    max-history: 10

# Application info
info:
  app:
    name: ${spring.application.name}
    description: Advanced Smart Appointment Booking System - User Service
    version: 1.0.0
    encoding: UTF-8
    java:
      version: ${java.version}
  author:
    name: Elyes
    email: elyes@example.com
  copyright:
    year: 2024-2025
    text: All Rights Reserved 